# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of3W0FXPy0UP6PAeFOJFOBHIhXV_bic4
"""

# Install Selenium
!pip install selenium

# Install Chromium and Chromium Driver
!apt-get update
!apt install chromium-chromedriver
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import pandas as pd
import numpy as np
import os

# Set up Chrome options
chrome_options = Options()
chrome_options.add_argument('--headless')  # Run in headless mode
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

#upload the sample csv file (see the previous step how to obtain this csv file)
sample = pd.read_csv(r'/content/SEC_suite_filing_info_test_sample.csv')

sample['tenk_url'] = 'https://www.sec.gov/Archives/' + sample['fname']

sample['MDA_name'] = sample['cik'].astype(int).astype(str) + '-' + sample['fdate'].astype(str) + '.txt'

sample['MDA_name'] = sample['MDA_name'].str.replace('/', '-')

save_directory = r'/content/saved_tenk'
os.makedirs(save_directory, exist_ok=True)

for index, row in sample.iterrows():
    # Get the URL from the tenk_url column
    url = row['tenk_url']

    # Get the filename from the MDA_name column
    filename = row['MDA_name']

    file_path = os.path.join(save_directory, f'{filename}.txt')

    !wget --header="User-Agent: YourCompanyName (+email@example.com)" -O "/content/saved_tenk/{filename}" "{url}"

#google colab doesn't allow users to download a folder directly, you need to change the folder into a zip file and download this zip file
!zip -r /content/saved_tenk.zip /content/saved_tenk